### PR TITLE
2.2.0 update - add gee and granite

### PR DESCRIPTION
**Pull request by mdh34**

### CODE REVIEW

**Comment by mdh34** [comment]
bot, build

**Comment by mdh34** [comment]
bot, build

**Comment by nedrichards** [comment]
fwiw you might actually want the Elementary BaseApp here: https://github.com/flathub/io.elementary.Loki.BaseApp/blob/master/io.elementary.Loki.BaseApp.json (to see what's inside).

A BaseApp copies the binaries from one app exactly into another ensuring that they'll get automatically deduplicated by flatpak if there's another app that uses them saving disk space (and usually data transfer) for users. There are a bunch of other apps using the BaseApp already if you want to check some examples: https://github.com/search?q=org%3Aflathub+io.elementary.Loki.BaseApp&type=Code it'll speed up your builds as well.

Obviously it doesn't work if you need custom configuration options but it can be a very handy concept.

**Comment by mdh34** [comment]
Thanks, I might wait till there's a Juno baseapp but that's really useful

**Pull request merged**
