### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by bbhtt**
Ping @mdh34, @bilelmoussaoui please review when you have time, thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
<del>Build fails, issue: https://github.com/mdh34/quickDocs/issues/59 (didn't notice this earlier :/)</del>

Should work now, the error was reported in https://github.com/mdh34/quickDocs/issues/53 and is fixed by https://github.com/mdh34/quickDocs/pull/55. The patch here was creating the issue.

**Comment by bbhtt** [comment]
bot, built

**Comment by bbhtt** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
bot, build

**Pull request merged**
